CREATE TYPE "genre" AS ENUM (
  'romance',
  'mystery',
  'fantasy/sci-fi',
  'autobiography',
  'instructional'
);

CREATE TABLE "book" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "title" varchar,
  "author_id" integer,
  "genre" genre,
  "publish_date" date,
  "publisher_id" integer
);

CREATE TABLE "author" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar
);

CREATE TABLE "publisher" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "customer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "username" varchar UNIQUE
);

CREATE TABLE "cart" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "customer_id" integer,
  "books" int[]
);

CREATE TABLE "author_book" (
  "author_id" integer,
  "book_author_id" integer,
  PRIMARY KEY ("author_id", "book_author_id")
);

ALTER TABLE "author_book" ADD FOREIGN KEY ("author_id") REFERENCES "author" ("id");

ALTER TABLE "author_book" ADD FOREIGN KEY ("book_author_id") REFERENCES "book" ("author_id");


ALTER TABLE "book" ADD FOREIGN KEY ("publisher_id") REFERENCES "publisher" ("id");

ALTER TABLE "cart" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id");

CREATE TABLE "book_cart" (
  "book_id" integer,
  "cart_books" int[],
  PRIMARY KEY ("book_id", "cart_books")
);

ALTER TABLE "book_cart" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id");

ALTER TABLE "book_cart" ADD FOREIGN KEY ("cart_books") REFERENCES "cart" ("books");

